### PR TITLE
Special session name treatment for Spotify

### LINKED ISSUE #179: Spotify shows window title and doesn't update.
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Describe the bug**
Spotify will show the entire track name in the device and will not update as we change tracks.

**To Reproduce**
1. Open up spotify and play a song.
2. Connect the device and launch maxmix.
3. Observe how it shows the name of the song playing.

**Expected behavior**
We would like to see "Spotify" instead of the entire song name which is pointless, especially since it doesn't update.

**Screenshots**

**System information:**
 - OS version: Windows 10
 - Firmware version: 1.2.0

**Additional context**

### PR DESCRIPTION
**Pull request by ItsLemmy**
## Issues
 - Fixes #179 

## Description
Added a special condition for Spotify where we don't attempt to use the window title as the session name.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Requested changes are in a branch
- [x] Compiled and tested requested changes on target hardware (PC, device)
- [ ] Updated the documentation, if necessary
- [ ] Updated the LICENSES file, if necessary
- [x] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository

### CODE REVIEW

File: Desktop/Application/MaxMix/Services/Audio/AudioSession.cs [hunk 1]
```diff
@@ -116,13 +116,28 @@ public bool IsMuted
...
-            if (string.IsNullOrEmpty(displayName)) { displayName = _session2.Process.ProcessName; }
-            if (string.IsNullOrEmpty(displayName)) { displayName = "Unnamed"; }
-            displayName = char.ToUpper(displayName[0]) + displayName.Substring(1);
+            if (IsSystemSound) {
+                displayName = "System Sounds";
+            }
+            else
+            {
+                var productName = _session2.Process.GetProductName();
+                if (productName == "Spotify")
```
Comment (XScorpion2) [inline Desktop/Application/MaxMix/Services/Audio/AudioSession.cs]: Don't special case a single application like this. Lets just prioritize GetProductName over MainWindowTitle

**Comment by ItsLemmy** [comment]
That's what I did at first, but I was unsure of the side effects for other apps.
As far as I know the specific "ifs" sequence was implemented for a reason by @t3knomanzer. 
But I'm fine with just swapping lines and having ProducteName first, which to me make more sense. 
Unless people run twice the same product with different audio session / window title.

**Comment by t3knomanzer** [comment]
The list of apps I have for testing are:
- VLC Media Player
- Spotify
- Steam
- Discord
- Cisco Webex
- Chrome

Let me re-prioritize product name over title and see if it works with all of those.

**Comment by t3knomanzer** [comment]
This is what I got with the product name prioritized over window title. Looks good to me.

Steam -> Steam Client Bootstrapper
Spotify -> Spotify
Discord -> Discord
Chrome -> Google Chrome
System Sounds -> System Sounds
VLC -> VLC Media Player

**Review by t3knomanzer — CHANGES_REQUESTED** [review]
I tested @XScorpion2 and "seems to be fine". I would recommend we give it a try.

**Comment by ItsLemmy** [comment]
Oki

**Review by t3knomanzer — APPROVED** [review]
